language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '11'
before_install:
- npm install -g npm@latest
- npm install -g greenkeeper-lockfile@1
install:
- npm install
before_script:
- greenkeeper-lockfile-update
script:
- npm run lint
- npm run build
after_script:
- greenkeeper-lockfile-upload
deploy:
  provider: script
  skip_cleanup: true
  script:
  - npm semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
