language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '11'
before_install:
- npm install -g greenkeeper-lockfile@1
install:
- npm install
before_script:
- greenkeeper-lockfile-update
script:
- npm run lint
- npm run build
after_script:
- greenkeeper-lockfile-upload
before_deploy:
- |
  if [ $TRAVIS_BRANCH == "master" ]; then
    echo "Create tar file before_deployment on master branch"
    mkdir release && tar --exclude='./dist/demo.html' -zcvf release/web3ready-release.tar.gz dist
  fi

jobs:
  include:
  # Define the release stage that runs semantic-release
  - stage: release
    node_js: '11'
    # Advanced: optionally overwrite your default `script` step to skip the tests
    # script: skip
    deploy:
      # Deploy github release
      - provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          branches:
            only:
              - master
      # Demo page for dev branch
      - provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: dist
        keep-history: false
        target-branch: gh-pages
        repo: web3ready/dev
        on:
          branches:
            only:
            - dev
      # Demo page for Releases
      - provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: dist
        keep-history: false
        target-branch: gh-pages
        repo: web3ready/latest
        on:
          branches:
            only:
            - master
