language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '11'
  - '10'
before_install:
- npm install -g npm@latest
- npm install -g greenkeeper-lockfile@1
install:
- npm install
before_script: greenkeeper-lockfile-update
script:
- npm run lint
after_script: greenkeeper-lockfile-upload
after_success:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script:
  - npx travis-deploy-once "npx semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
