language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '11'
before_install:
- npm install -g greenkeeper-lockfile@1
install:
- npm install
before_script:
- greenkeeper-lockfile-update
script:
- npm run lint
- npm run build
after_script:
- greenkeeper-lockfile-upload

jobs:
  include:
  # Define the release stage that runs semantic-release
  - stage: release
    node_js: '11'
    # Advanced: optionally overwrite your default `script` step to skip the tests
    # script: skip
    deploy:
      # Deploy github release
      - provider: script
        skip_cleanup: true
        tarballDir: "dist",
        script: npx semantic-release
        on:
          branch: master
      # Demo page for dev branch
      - provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: dist
        keep-history: false
        target-branch: gh-pages
        repo: web3ready/dev
        on:
          branch: dev
      # Demo page for Releases
      - provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: dist
        keep-history: false
        target-branch: gh-pages
        repo: web3ready/latest
        on:
          branch: master
